---
title: "p8105_hw5_yl6109"
author: "Yurou Liu"
date: "2025-11-05"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(purrr)
library(tidyverse)
library(dplyr)
library(broom)
library(patchwork)
```

## Problem 1

```{r}
# write function
bd_dup = function(n) {
  if (n <= 0){stop("input must be positive integer")}
  if (n > 365){return(TRUE)}
  birthday = sample(1:365, size = n, replace = TRUE)
  have_dup = any(duplicated(birthday))
  return(have_dup)
}

#simulation
bd_sim = function(num_of_sim, group_size_min, group_size_max){
  group_sizes = group_size_min:group_size_max
  prob = numeric(length(group_sizes))
  
  for (i in 1:length(group_sizes)){
    n = group_sizes[i]
    result = replicate(num_of_sim, bd_dup(n))
    prob[i] = mean(result)
  }
  
  result_df = tibble(
      group_size = group_sizes,
      probability = prob
    )
  return(result_df)
}

results = bd_sim(10000, 2, 50)
results %>% 
  ggplot(aes(x = group_size, 
             y = probability)) + 
  geom_col() + 
  labs(title = "probability of at least two people having same birthday", 
       x = "group size", 
       y = "prbability")
```


## Problem 2

```{r}
# simulation
n = 30
sigma = 5
mu_values = c(0, 1, 2, 3, 4, 5, 6)
n_sim = 50

results = data.frame()

for (mu in mu_values) {
  for (i in 1:n_sim) {
    x = rnorm(n, mean = mu, sd = sigma)
    t_test = t.test(x, mu = 0)
    tidy_result = broom::tidy(t_test)
    results = rbind(results, data.frame(mu_true = mu,
                                        mu_hat = tidy_result$estimate, 
                                        p_value = tidy_result$p.value, 
                                        rejected = tidy_result$p.value < 0.05))
  }
}

# df for plots
p2_plot_df = results %>% 
  group_by(mu_true) %>% 
  summarise(power = mean(rejected), 
           mean_mu_hat = mean(mu_hat), 
           rejected_mean_mu_hat = mean(mu_hat[rejected == TRUE]))

# draw plot

# power vs true mean
p2_plot_df %>% 
  ggplot(aes(x = mu_true, 
             y = power)) + 
  geom_point() + 
  labs(title = "power vs true mean",
       x = "true mean value",
       y = "power", 
       caption = "n = 30, sigma = 5, alpha = 0.05, 5000 simulations for each")

# avg mu hat for total (and avg mu hat in rejected) vs true mean
p22 = p2_plot_df %>% 
  ggplot(aes(x = mu_true, 
             y = mean_mu_hat)) + 
  geom_point() + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "gray") +
  labs(title = "avg mu hat for total vs true mean",
       x = "true mean value", 
       y = "estimated mean value")

p23 = p2_plot_df %>% 
  ggplot(aes(x = mu_true,
             y = rejected_mean_mu_hat)) + 
  geom_point() + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "gray") +
  labs(title = "avg mu hat in rejected vs true mean" ,
       x = "true mean value", 
       y = "estimated mean value for rejected tests")

combined_plot = p22 + p23
combined_plot
```

## problem 3

```{r}
# deal with data
homicide_df = read_csv("./data/homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(city_state = paste(city, state, sep = ", "))

homicide_summary = homicide_df %>% 
  group_by(city) %>% 
  summarize(total_homicides = n(), 
            unsolved_homicides = sum(disposition %in% c("Closed without arrest", "Open/No arrest"))) %>% 
  print()

# prop test for Baltimore and pull values
btm_df = homicide_summary %>% 
  filter(city == "Baltimore")

result_baltimore = prop.test(
  x = pull(btm_df, unsolved_homicides), 
  n = pull(btm_df, total_homicides)
  )

tidy_prop = tidy(result_baltimore) %>% 
  print()

estimated_prop = pull(tidy_prop, estimate)
conf_low = pull(tidy_prop, conf.low)
conf_high = pull(tidy_prop, conf.high)

# for each city, prop test
city_results = homicide_summary %>% 
  mutate(
    test_result = map2(unsolved_homicides, total_homicides, 
                       ~tidy(prop.test(x = .x, n = .y)))) %>% 
  unnest(test_result) %>%
  select(city, estimate, conf.low, conf.high, total_homicides, unsolved_homicides) %>%
  print()

# draw plot
city_results %>% 
  mutate(city = fct_reorder(city, estimate)) %>% 
  ggplot(aes(x = estimate, 
             y = city)) + 
  geom_point() + 
  geom_errorbar(aes(xmin = conf.low, 
                    xmax = conf.high)) + 
  labs(title = "estimated unsolved homicide porportion of different cities", 
       x = "estimated porportion of unsolved homicide",
       y = NULL, 
      caption = "error bars represent the 95% CI") + 
  theme(axis.text.y = element_text(size = 6))
```
